// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKDhAbNblkx2VJeB3-yVZR4At30tWAbJ0',
    appId: '1:858556351786:web:7dc8247c2f1fcc37e70a53',
    messagingSenderId: '858556351786',
    projectId: 'cocunstruct',
    authDomain: 'cocunstruct.firebaseapp.com',
    storageBucket: 'cocunstruct.firebasestorage.app',
    measurementId: 'G-MGFN0E6WH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOeBCoIlOYFg_MhAgf6S7BZLaZ2-4rzhs',
    appId: '1:858556351786:android:fed512f1c480db33e70a53',
    messagingSenderId: '858556351786',
    projectId: 'cocunstruct',
    storageBucket: 'cocunstruct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB3vsqVp1nVt57JsnR3xuO2p9TQEmTT8c',
    appId: '1:858556351786:ios:680674f8ba9c6ebce70a53',
    messagingSenderId: '858556351786',
    projectId: 'cocunstruct',
    storageBucket: 'cocunstruct.firebasestorage.app',
    iosBundleId: 'com.example.constructApp',
  );
}
