// Mocks generated by Mockito 5.4.5 from annotations
// in construct_app/test/features/project/presentation/bloc/project_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:construct_app/core/error/failures.dart' as _i6;
import 'package:construct_app/features/project/domain/entities/project.dart'
    as _i7;
import 'package:construct_app/features/project/domain/repositories/project_repository.dart'
    as _i2;
import 'package:construct_app/features/project/domain/usecases/get_projects_usecase.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProjectRepository_0 extends _i1.SmartFake
    implements _i2.ProjectRepository {
  _FakeProjectRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProjectsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProjectsUseCase extends _i1.Mock
    implements _i4.GetProjectsUseCase {
  MockGetProjectsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProjectRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProjectRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProjectRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Project>>> call(
    _i4.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Project>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Project>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Project>>>);
}
